version: '3.7'
services:
  produk-service:
        build: produk-service
        environment: 
          MYSQL_HOST: 'mysql:3306'
          MYSQL_DATABASE: 'nidzam-soluix'
          MYSQL_USER: 'root'
          MYSQL_PASSWORD: 'password'
        ports:        
          - "9000:9000"
        expose:
          - "9000"
        depends_on:
          - mysql
        restart: always
  mysql:
    image: mysql:5.7
    container_name: 'mysql_nidzam_soluix'
    environment:
      MYSQL_DATABASE: 'nidzam-soluix'
      MYSQL_HOST: 'localhost:3306'
      MYSQL_USER: 'mysql'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - "3306:3306"
    restart: always
    volumes:     
      - ./db/nidzam-ecomerce.sql:/docker-entrypoint-initdb.d/init.sql
  
            